# LTS Bookworm (Debian 11) end of life: 2026-08-31 (https://wiki.debian.org/DebianReleases)
# LTS Hydrogen (Node 20) end of life: 2026-04-31 (https://nodejs.org/en/about/previous-releases)
# Using bullseye instead of bookwork due to an SSL error between node and a dependency
image: node:hydrogen-bookworm

stages:
  - build
  - test
  - deploy

before_script:
  - yarn install --cache-folder .yarn


# These folders are cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
    - node_modules/
    - .yarn
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

yarn:install:
  stage: build
  script: |-3
     # Install via yarn with frozen-lockfile to allow reproducible dependencies and 
     # check-files option to check if the node_modules cache is valid.
     # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
     yarn install --frozen-lockfile --check-files --non-interactive --cache-folder .yarn
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  cache:
    paths:
    - .yarn
    - node_modules

test:unit:
  stage: test
  needs: ["yarn:install"]
  script:
    - npm run test:unit
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  cache:
    paths:
    - .yarn
    - node_modules

test:gatsby:
  stage: test
  needs: ["yarn:install"]
  script:
    - ./node_modules/.bin/gatsby info
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  cache:
    paths:
    - .yarn
    - node_modules

pages:
  stage: deploy
  needs: 
    - yarn:install
    - test:unit
    - test:gatsby
  script:
    - NODE_OPTIONS=--openssl-legacy-provider ./node_modules/.bin/gatsby build --prefix-paths
  cache:
    paths:
    - .yarn
    - node_modules
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
